# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 46466424c6ac24e502535a8d7ca7038db154aa11228e5eeba1b756cd6d39b1b985e0bfb0958e1df938eeed929b7dcfd496c4013bd57ed7deda9a6bf522f7b52e

test:
  secret_key_base: e77d559d55be166cdc94d29cde844d199d0fb1792031cd5bd91844daf11dab24f545be00a19d2d6174e155dd3c02cb6dc8f25a557b57848a5baa4e593fe33fad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
